export const environment = {
  production: true,
  REST_BASE_URL: '/',
  WEBROOT_BASE_URL: '',
  CAPTCHA_SECRET_KEY: '@CAPTCHA_SECRET_KEY',
  MATOMO_SITE_ID: '@MATOMO_SITE_ID',
  MATOMO_TRACKER_URL: '@MATOMO_TRACKER_URL'
};
